export enum FlowNodeType {
  start = 'start',
  message = 'message',
  buttons = 'buttons',
  dynamicButtons = 'dynamicButtons',
  buttonsItem = 'buttonsItem',
  articles = 'articles',
  cards = 'cards',
  dynamicCards = 'dynamicCards',
  transfer = 'transfer',
  closeConversation = 'closeConversation',
  goToStep = 'goToStep',
  goToFlow = 'goToFlow',
  collectDetails = 'collectDetails',
  tool = 'tool',
  toolResult = 'toolResult',
  setAttribute = 'setAttribute',
  addTags = 'addTags',
  branches = 'branches',
  branchesItem = 'branchesItem',
  placeholder = 'placeholder',
}
